# This is a basic workflow to help you get started with Actions

name: Linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-linters:
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#     - name: update brew
#       run: brew update
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      
    - name: install infer
      run:  brew install infer
      
    - name: Check out Git repository
      uses: actions/checkout@v2
      
#     - name: Xcode version
#       run: /usr/bin/xcodebuild -version
#     - name: Install Dependencies
#       run: pod install --repo-update

    # Runs a single command using the runners shell
    - name: Run Linters
      uses: AppMonet/lint-action@master
      with:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.github_token }}
        infer: true
        infer_args: xcodebuild -scheme AppMonet_Bidder -workspace AppMonet.xcworkspace -sdk iphonesimulator
        
        intfer: true
        intfer_args: xcodebuild -scheme AppMonet_Bidder -workspace AppMonet.xcworkspace -sdk iphonesimulator
